-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 18:14:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wehelp_s3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wehelp_s3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wehelp_s3` DEFAULT CHARACTER SET utf8 ;
USE `wehelp_s3` ;

-- -----------------------------------------------------
-- Table `wehelp_s3`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wehelp_s3`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(50) NOT NULL,
  `message` VARCHAR(1000) NOT NULL,
  `creatTime` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
